# These are supported funding model platforms

# Uncomment and add your details if you want to accept sponsorships:
# github: [mavnezz]
# ko_fi: YOUR_USERNAME
# patreon: YOUR_USERNAME
# buy_me_a_coffee: YOUR_USERNAME
